### ISSUE TITLE
Help configuring route enhancer

### ISSUE THREAD

**Issue by SilentHunter124** [derhansen/sf_event_mgt#1214]
### Extension version
6.5.2

### Short problem description
How do I get route enhancers running? I just wanted the detail page of an event printed on flyers with an qr code. Unfortunately the slug generated on one event (multilanguage says: /de/{event_title})

### Steps to reproduce
1. Create some events with english and german descriptions
2. pinned url slug to something with title
3. configured site.yaml:
```
routeEnhancers:
  EventDetailPlugin:
    type: Extbase
    limitToPages:
      - 60
    extension: SfEventMgt
    plugin: Pieventdetail
    routes:
      -
        routePath: '/de/{event_title}'
        _controller: 'Event::detail'
        _arguments:
          event_title: event
      -
        routePath: '/de/{event_title}/ical'
        _controller: 'Event::icalDownload'
        _arguments:
          event_title: event
    defaultController: 'Event::detail'
    aspects:
      event_title:
        type: PersistedAliasMapper
        tableName: tx_sfeventmgt_domain_model_event
        routeFieldName: slug
```

### Expected behaviour
The displayed slug url of an event should display detail page of the event.

### Actual behaviour
Typo3 Responds with 404 Page

### Server configuration
**TYPO3 version:**
11.5.32

**PHP version:**
8.1.27
