### ISSUE TITLE
Hide specific module actions in the backend toolbar

### ISSUE THREAD

**Issue by sukitsubaki** [derhansen/sf_event_mgt#1317]
I need to hide specific module actions/buttons in the EXT:sf_event_mgt backend module's toolbar ([available actions](https://docs.typo3.org/p/derhansen/sf_event_mgt/main/en-us/ForEditors/Backend/BackendModule/Index.html#available-actions)). Specifically, I want to show only the "Create new event" button and hide all other buttons ("Create new location", "Create new organizer", "Create new speaker", and "Hide/delete expired registrations") for a backend user group.

### Environment
- TYPO3 version: 13.4.5
- sf_event_mgt version: 8.1.1

### What I've tried
I already set up proper backend user permissions so that users cannot perform these actions, but the buttons are still visible, which is confusing to our editors. 

I've attempted several configuration approaches:

1. User TSconfig:
```
options.hideModules {
  web_SfEventMgtTxSfeventmgtM1 {
    location = 1
    organizer = 1
    speaker = 1
    registration = 1
  }
}
```

2. TypoScript setup:
```
module.tx_sfeventmgt {
  settings {
    enabledActions {
      newEvent = 1
      newLocation = 0
      newOrganizer = 0
      newSpeaker = 0
      hideDeleteExpired = 0
    }
  }
}
```

3. Alternative TypoScript setup:
```
module.tx_sfeventmgt_events {
  settings {
    enabledActions {
      newEvent = 1
      newLocation = 0
      newOrganizer = 0
      newSpeaker = 0
      hideDeleteExpired = 0
    }
  }
}
```

None of these approaches has been successful in hiding the buttons.

### Related feature
I noticed that a feature was previously added to hide certain module actions (Feature #637), which implemented the `IsActionEnabledViewHelper`, but this appears to be limited to the `notify` and `export` actions in the event list view, and doesn't control the toolbar buttons.

### Question
Am I missing something or is there already a way to configure the toolbar buttons via TypoScript? I noticed the enabledActions configuration and the `IsActionEnabledViewHelper`, but they seem to be limited to the `notify` and `export` actions in the event list view.

Is there a similar configuration option for the toolbar buttons that I've overlooked? Or would an extension of the `enabledActions` configuration to include these toolbar buttons be necessary?

As a workaround, I'm currently considering hiding these buttons with custom CSS, but would prefer a proper configuration option consistent with the existing feature.

**Comment by sukitsubaki** [comment]
> As a workaround, I'm currently considering hiding these buttons with custom CSS, but would prefer a proper configuration option consistent with the existing feature.

```css
/* Hide all buttons in the group except the first one */
.module-docheader-bar .btn-group a:not(:first-child) {
    display: none !important;
}

/* Hide the "Hide/delete expired registrations" button (which is outside the group) */
.module-docheader-bar a[title="Hide/delete expired registrations"],
.module-docheader-bar a[data-title="Hide/delete expired registrations"] {
    display: none !important;
}

/* Alternative approach if the above doesn't work: identify buttons by their SVG icons */
.module-docheader-bar [data-identifier="ext-sfeventmgt-location"],
.module-docheader-bar [data-identifier="ext-sfeventmgt-organisator"],
.module-docheader-bar [data-identifier="ext-sfeventmgt-speaker"],
.module-docheader-bar [data-identifier="ext-sfeventmgt-action-handle-expired"] {
    display: none !important;
}
```
